/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as B2cRouteImport } from './routes/b2c'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GardenIndexRouteImport } from './routes/garden.index'
import { Route as GardenPlantIdRouteImport } from './routes/garden.$plantId'

const B2cRoute = B2cRouteImport.update({
  id: '/b2c',
  path: '/b2c',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenIndexRoute = GardenIndexRouteImport.update({
  id: '/garden/',
  path: '/garden/',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenPlantIdRoute = GardenPlantIdRouteImport.update({
  id: '/garden/$plantId',
  path: '/garden/$plantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b2b': typeof B2bRoute
  '/b2c': typeof B2cRoute
  '/garden/$plantId': typeof GardenPlantIdRoute
  '/garden/': typeof GardenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b2b': typeof B2bRoute
  '/b2c': typeof B2cRoute
  '/garden/$plantId': typeof GardenPlantIdRoute
  '/garden': typeof GardenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b2b': typeof B2bRoute
  '/b2c': typeof B2cRoute
  '/garden/$plantId': typeof GardenPlantIdRoute
  '/garden/': typeof GardenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b2b' | '/b2c' | '/garden/$plantId' | '/garden/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b2b' | '/b2c' | '/garden/$plantId' | '/garden'
  id: '__root__' | '/' | '/b2b' | '/b2c' | '/garden/$plantId' | '/garden/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  B2bRoute: typeof B2bRoute
  B2cRoute: typeof B2cRoute
  GardenPlantIdRoute: typeof GardenPlantIdRoute
  GardenIndexRoute: typeof GardenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/b2c': {
      id: '/b2c'
      path: '/b2c'
      fullPath: '/b2c'
      preLoaderRoute: typeof B2cRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden/': {
      id: '/garden/'
      path: '/garden'
      fullPath: '/garden/'
      preLoaderRoute: typeof GardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden/$plantId': {
      id: '/garden/$plantId'
      path: '/garden/$plantId'
      fullPath: '/garden/$plantId'
      preLoaderRoute: typeof GardenPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  B2bRoute: B2bRoute,
  B2cRoute: B2cRoute,
  GardenPlantIdRoute: GardenPlantIdRoute,
  GardenIndexRoute: GardenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
